### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by Hydrotoast** [btwardow/FactorizationMachines.jl#1]
So that I could contribute

**Comment by btwardow** [comment]
Yes. How can I help You? ;-) However, right now I'm coding more for my phd using python+theano.

**Comment by Hydrotoast** [comment]
I would like to contribute for the following TODOs:
- Add classifiation. Right now only regression task is handled
- Adaptive SGD

In addition to doing some code cleanup, performance optimizations, and making this an official Julia package.

Just verifying that it would be possible to send you PRs if you have time to review the code sometime this week.

**Comment by btwardow** [comment]
Superb. Sounds great! 
I will be happy to do PR review :-)
